# Generated by Django 5.0.6 on 2024-10-24 04:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=60)),
                ('number', models.CharField(max_length=20)),
                ('crossing', models.CharField(max_length=60)),
                ('cologne', models.CharField(max_length=60)),
                ('zip_code', models.IntegerField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nomber', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=40)),
                ('validity', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='rfc',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='license',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.license'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('departament', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.departament')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.role'),
        ),
    ]
