# Generated by Django 5.0.6 on 2024-11-11 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Type_Maintenance',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('chapter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('cont_days', models.IntegerField(max_length=3, null=True)),
                ('cont_years', models.IntegerField(max_length=3, null=True)),
                ('cont_hours', models.IntegerField(max_length=6, null=True)),
                ('cont_tbo', models.IntegerField(max_length=6, null=True)),
                ('number_ata', models.ManyToManyField(null=True, to='maintenance.chapter')),
                ('type_maintenance', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='maintenance.type_maintenance')),
            ],
        ),
    ]
