# Generated by Django 5.0.6 on 2024-12-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0002_alter_service_id_alter_service_senior_service'),
        ('engines', '0002_alter_engine_engine_model'),
        ('propellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plane',
            name='engines',
            field=models.ManyToManyField(blank=True, to='engines.engine'),
        ),
        migrations.AddField(
            model_name='plane',
            name='propellers',
            field=models.ManyToManyField(blank=True, to='propellers.propeller'),
        ),
    ]
