# Generated by Django 5.0.6 on 2024-12-13 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aircrafts', '0003_plane_engines_plane_propellers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plane',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aircrafts.plane_model'),
        ),
        migrations.AlterField(
            model_name='plane',
            name='senior_service',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='plane',
            name='time',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
