# Generated by Django 5.0.6 on 2024-12-11 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='engine_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engines.model_engine'),
        ),
    ]
